[pytest]
markers =
    regression: Tests críticos de regresión
    smoke: Tests críticos de humo
    login: Tests de funcionalidad de login
    catalogo: Tests de funcionalidad de catálogo
    carrito: Tests de funcionalidad de carrito