[pytest]
addopts =  -v --html=reports/reports.html --self-contained-html

html_report_title = TalentoLab - Resumen de ejecución
html_report_description = Suite UI + API completa

# Markers

markers =
    regression: Tests críticos de regresión
    smoke: Tests críticos de humo
    login: Tests de funcionalidad de login
    catalogo: Tests de funcionalidad de catálogo
    carrito: Tests de funcionalidad de carrito
    api: Test de api
    e2e: Pruebas de flujo end-to-end
    flaky: Retries para test con posibilidad de fallo intermitente por red
    ui: Pruebas de interfaz